// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAV.Interventions.Infrastructure.Data;

#nullable disable

namespace SAV.Interventions.Infrastructure.Migrations
{
    [DbContext(typeof(InterventionsDbContext))]
    [Migration("20251201122549_AddTechnicienEntity")]
    partial class AddTechnicienEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIntervention")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstGratuite")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MontantMainOeuvre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReclamationId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicienId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicienNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TechnicienId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.PieceUtilisee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<int>("PieceDetacheeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("PiecesUtilisees");
                });

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.Technicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Techniciens");
                });

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("SAV.Interventions.Domain.Entities.Technicien", "Technicien")
                        .WithMany("Interventions")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.PieceUtilisee", b =>
                {
                    b.HasOne("SAV.Interventions.Domain.Entities.Intervention", "Intervention")
                        .WithMany("PiecesUtilisees")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.Intervention", b =>
                {
                    b.Navigation("PiecesUtilisees");
                });

            modelBuilder.Entity("SAV.Interventions.Domain.Entities.Technicien", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
