// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAV.Notifications.Infrastructure.Data;

#nullable disable

namespace SAV.Notifications.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAV.Notifications.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Statut");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SAV.Notifications.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorpsHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("NotificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorpsHtml = "\r\n                    <h1>Bienvenue {{ClientNom}}!</h1>\r\n                    <p>Merci de vous être inscrit sur notre plateforme SAV.</p>\r\n                    <p>Vous pouvez maintenant gérer vos articles et créer des réclamations.</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2141),
                            IsActive = true,
                            Sujet = "Bienvenue chez SAV Pro!",
                            Type = "Bienvenue"
                        },
                        new
                        {
                            Id = 2,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>Votre réclamation #{{ReclamationId}} pour l'article <strong>{{ArticleNom}}</strong> a été créée avec succès.</p>\r\n                    <p>Notre équipe va traiter votre demande dans les plus brefs délais.</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2146),
                            IsActive = true,
                            Sujet = "Réclamation #{{ReclamationId}} créée",
                            Type = "ReclamationCreee"
                        },
                        new
                        {
                            Id = 3,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>Le statut de votre réclamation #{{ReclamationId}} a été mis à jour.</p>\r\n                    <p><strong>Nouveau statut:</strong> {{Statut}}</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2149),
                            IsActive = true,
                            Sujet = "Mise à jour réclamation #{{ReclamationId}}",
                            Type = "ReclamationStatutChange"
                        },
                        new
                        {
                            Id = 4,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>Une intervention a été planifiée pour votre réclamation.</p>\r\n                    <p><strong>Date:</strong> {{DateIntervention}}</p>\r\n                    <p>Un technicien vous contactera prochainement.</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2151),
                            IsActive = true,
                            Sujet = "Intervention planifiée - {{DateIntervention}}",
                            Type = "InterventionPlanifiee"
                        },
                        new
                        {
                            Id = 5,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>L'intervention pour votre réclamation #{{ReclamationId}} est terminée.</p>\r\n                    <p>Merci de votre confiance!</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2152),
                            IsActive = true,
                            Sujet = "Intervention terminée - Réclamation #{{ReclamationId}}",
                            Type = "InterventionTerminee"
                        },
                        new
                        {
                            Id = 6,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>Nous avons bien reçu votre paiement de <strong>{{Montant}}€</strong>.</p>\r\n                    <p>Merci pour votre règlement!</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2154),
                            IsActive = true,
                            Sujet = "Paiement reçu - {{Montant}}€",
                            Type = "PaiementRecu"
                        },
                        new
                        {
                            Id = 7,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>La garantie de votre article <strong>{{ArticleNom}}</strong> expire le <strong>{{DateExpiration}}</strong>.</p>\r\n                    <p>Pensez à vérifier votre équipement avant cette date.</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2155),
                            IsActive = true,
                            Sujet = "Votre garantie expire bientôt!",
                            Type = "GarantieExpiration"
                        },
                        new
                        {
                            Id = 8,
                            CorpsHtml = "\r\n                    <h1>Bonjour {{ClientNom}},</h1>\r\n                    <p>Nous vous rappelons qu'une facture de <strong>{{Montant}}€</strong> est en attente de paiement.</p>\r\n                    <p>Merci de régulariser votre situation.</p>\r\n                ",
                            CreatedAt = new DateTime(2025, 12, 14, 18, 48, 24, 899, DateTimeKind.Utc).AddTicks(2157),
                            IsActive = true,
                            Sujet = "Rappel: Facture en attente de paiement",
                            Type = "RappelPaiement"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
